stages:
  - deploy

deploy_production:
  stage: deploy
  # Use a minimal image with SSH client
  image: kroniak/ssh-client
  # This section runs before the main script
  before_script:
    - eval $(ssh-agent -s)
    - chmod 600 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SSH_USER_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  script:
    - |
      ssh $SSH_USER_HOST "
        if [ ! -d "$PROJECT_PATH" ]; then
          echo 'Project directory does not exist. Cloning repository...';
          git clone git@gitlab.unpam.ac.id:${CI_PROJECT_PATH}.git $PROJECT_PATH;
        fi;
        cd $PROJECT_PATH && ./deploy.sh
      "
  
  environment:
    name: production
    url: http://10.11.0.20
  
  # This job will only run on pushes to the 'develop' branch
  only:
    - develop